---
sidebar: sidebar 
permalink: ONTAP/fix-blockers-warnings.html 
keywords: fix ontap blockers and warnings, ontap update precheck, acknowledge warnings 
summary: Beheben Sie ONTAP-Blocker und bestätigen Sie Warnungen, die verhindern, dass Sie das ONTAP-Update abschließen. 
---
= Beheben Sie alle Blocker, die BlueXP -Softwareupdates verwenden, bevor Sie ein ONTAP-Upgrade durchführen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die ONTAP Zielversion für Ihr ONTAP Storage-System ermittelt haben, sollten Sie alle Blocker reparieren und bestätigen sowie die Warnungen vor dem Aktualisieren des ONTAP Storage-Systems prüfen.

.Erforderliche BlueXP -Rolle:
Organisationsadministrator, Ordner- oder Projektadministrator, Speicheradministrator oder Systemintegritätsspezialist. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]

Das Beheben und Quittieren aller Blocker ist obligatorisch und gewährleistet einen nahtlosen Softwareupdateprozess.

.Schritte
. Wählen Sie in der linken BlueXP -Navigation *Systemzustand > Softwareupdates*.
+
Die Liste der Cluster, für die ein Softwareupdate erforderlich ist, wird angezeigt.

. Ermitteln Sie die ONTAP Zielversion für Ihr Storage-System. Informationen zur Identifizierung der ONTAP-Zielversion finden Sie unter link:../ONTAP/choose-ontap-910-later.html["Vergleichen Sie ONTAP Versionen, um sich mit BlueXP  Software Updates vor- und zurück zu informieren"].
. Nachdem Sie sich für die ONTAP Zielversion entschieden haben, wählen Sie *Für Update vorbereiten*, um den Update-Vorgang zu starten.
+
Die Liste der Blocker und Warnungen wird angezeigt.

. Wählen Sie den Blocker aus, um die Anweisungen zum Beheben des Blocker anzuzeigen.
. Führen Sie die angegebenen Schritte zum Beheben des Blocker manuell aus.
. Wählen Sie die behobenen Blocker aus und wählen Sie *Auswahl bestätigen*, um zu bestätigen, dass die Blocker behoben wurden.



NOTE: Sie müssen alle Blocker beheben und bestätigen, um mit der Aktualisierung fortzufahren.

. Wählen Sie die Registerkarte *Warnungen*, um die Warnungen zu überprüfen, bevor Sie mit der Softwareaktualisierung fortfahren.
. Wählen Sie die Registerkarte *Bestätigen*, um die behobenen Blocker anzuzeigen.
. Wählen Sie *Mit Aktualisierung fortfahren*, um mit dem Aktualisierungsvorgang fortzufahren.

