---
sidebar: sidebar 
permalink: get-started/prerequisites-ontap-update.html 
keywords: prerequisites for ontap update, ontap update requirements, ontap update versions, prepare for ontap update 
summary: Überprüfen Sie die Voraussetzungen und Anforderungen, bevor Sie mit dem ONTAP Update fortfahren. 
---
= Bereiten Sie die Aktualisierung von ONTAP mithilfe von BlueXP -Softwareupdates vor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Voraussetzungen und Anforderungen überprüfen, bevor Sie mit dem ONTAP Update fortfahren. Mithilfe von BlueXP -Softwareupdates können Sie die Einsatzbereitschaft Ihrer Betriebsumgebung, der Anmeldung, des Netzwerkzugriffs und des Webbrowsers überprüfen.

.Erforderliche BlueXP -Rolle:
Organisationsadministrator, Ordner- oder Projektadministrator, Speicheradministrator, Speicherbetrachter oder Systemintegritätsspezialist. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]

Um BlueXP  Software-Updates zu verwenden, sollten Sie sicherstellen, dass Ihre Umgebung alle Anforderungen erfüllt.

* In BlueXP  wird eine Arbeitsumgebung eingerichtet.
* Administratoranmeldeinformationen sind für das gewünschte Cluster verfügbar, während das Softwareupdate durchgeführt wird.
* Alle Nodes im Cluster senden AutoSupport-Daten.
* Alle Nodes sollten unter ONTAP 9.10 oder höher ausgeführt werden.
* Nodes sollten sich nicht in einer MetroCluster-Konfiguration befinden.

