---
sidebar: sidebar 
permalink: get-started/software-updates-faq.html 
keywords: ontap update faq, ontap update frequently asked questions, software updates faq, software updates frequently asked questions, troubleshooting 
summary: Hier finden Sie Antworten auf häufig gestellte Fragen zu BlueXP  Software-Updates. 
---
= Häufig gestellte Fragen zu BlueXP -Software-Updates
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie mehr über BlueXP -Software-Updates erfahren möchten oder Hilfe bei der Fehlerbehebung benötigen, können Sie diese Fragen zur schnellen Antwort durchgehen.

*Was ist die URL für die BlueXP -Software-Updates?*

Geben Sie für die URL in einem Browser Folgendes ein: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] , um auf die BlueXP  Konsole zuzugreifen.

*Benötigen Sie eine Lizenz, um BlueXP -Software-Updates zu nutzen?*

Eine NetApp Lizenzdatei (NetApp License File, NLF) ist nicht erforderlich.

*Warum kann ich den Cluster auch nach der Aktualisierung der ONTAP-Version des Clusters nicht im History Tab anzeigen?*

Es dauert 2 bis 3 Stunden, bis das Cluster auf der Registerkarte „Verlauf“ angezeigt wird. Nach der Aktualisierung der ONTAP-Version des Clusters wird AutoSupport generiert. Es dauert 2 bis 3 Stunden, bis die AutoSupport-Daten verarbeitet und die neueste Version von ONTAP wiedergegeben werden.

*Warum sehe ich die ältere Version von ONTAP im Dashboard für Softwareupdates, selbst wenn ich die ONTAP-Version des Clusters aktualisiert habe?*

Es dauert 2 bis 3 Stunden, bis das Cluster auf der Registerkarte „Verlauf“ angezeigt wird. Nach der Aktualisierung der ONTAP-Version des Clusters wird AutoSupport generiert. Es dauert 2 bis 3 Stunden, bis die AutoSupport-Daten verarbeitet und die neueste Version von ONTAP wiedergegeben werden.

*Warum sehe ich verschiedene Bildschirme für verschiedene Updates?*

Dies liegt an der aktuellen ONTAP-Version und der Nichtverfügbarkeit des BlueXP -Connectors für Cluster. Ein BlueXP -Connector führt das ONTAP-Update innerhalb von BlueXP  durch und erfordert nicht, dass Sie für ein Update aus BlueXP  wechseln müssen. Wenn Sie keinen BlueXP -Anschluss haben, werden Sie zu System Manager umgeleitet und müssen die ONTAP-Cluster-Anmeldedaten erneut eingeben. Informationen über den ONTAP-Aktualisierungsprozess für verschiedene Versionen von ONTAP finden Sie unter link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Unterstützte ONTAP-Systeme"].

*Was brauche ich, um Cluster zu entdecken?*

Um ein ONTAP Update für das gewünschte Cluster durchzuführen, benötigen Sie die ONTAP-Cluster-IP und die Admin-Anmeldedaten für die Verbindung zum Cluster. Im Rahmen der Cluster-Erkennung müssen Sie die Angaben angeben, damit das ONTAP Update automatisch ausgeführt werden kann.
