---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'software updates, ontap update, what"s new, enhancements' 
summary: Lernen Sie die neuen Funktionen und Erweiterungen der BlueXP  Software-Updates kennen. 
---
= Neuerungen bei BlueXP  Software-Updates
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informieren Sie sich über Neuerungen bei BlueXP  Software-Updates.



== 12 Mai 2025



=== BlueXp-Zugriffsrolle erforderlich

Sie benötigen nun eine der folgenden Zugriffsrollen, um Softwareupdates zu installieren: *Organisationsadministrator*, *Ordner- oder Projektadministrator*, *Speicheradministrator*, *Speicherbetrachter* oder *Speicherintegritätsspezialist*. Benutzer mit der Rolle „Speicherbetrachter“ verfügen über verschiedene Berechtigungen für Softwareupdates, können diese jedoch nicht installieren. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]



== Bis 02. April 2025



=== Risikoverringerung

Im Abschnitt „Zusammenfassung“ der BlueXP -Softwareupdates können Sie nun die Gesamtzahl der Risiken anzeigen, die durch das Betriebssystem-Update vermindert werden können. Auf diese Weise können Benutzer die Sicherheits- und Stabilitätsverbesserungen auf ihrer Installationsbasis bewerten.



== 07 August 2024



=== ONTAP-Update

Der BlueXP  Service für Softwareupdates bietet Benutzern ein nahtloses Update, da Risiken verringert und sichergestellt wird, dass Kunden die ONTAP Funktionen in vollem Umfang nutzen können.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  Software-Updates"].
